// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUO1iwKkHVU3O2oT7JGsUzfjxetp_gRCg',
    appId: '1:571188881615:web:1d7b9180d832207d6e2fba',
    messagingSenderId: '571188881615',
    projectId: 'sneakers-30b66',
    authDomain: 'sneakers-30b66.firebaseapp.com',
    storageBucket: 'sneakers-30b66.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOToxWWnSRKjJoKADAUN1CDoOQTnJV1jU',
    appId: '1:571188881615:android:d43b1da16097a7dc6e2fba',
    messagingSenderId: '571188881615',
    projectId: 'sneakers-30b66',
    storageBucket: 'sneakers-30b66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Qau24nMVXQijHQ8mDdBOf1x3D958FqA',
    appId: '1:571188881615:ios:e79a45f4ad7ce72a6e2fba',
    messagingSenderId: '571188881615',
    projectId: 'sneakers-30b66',
    storageBucket: 'sneakers-30b66.firebasestorage.app',
    iosBundleId: 'com.example.sneakers',
  );
}
